### ISSUE TITLE
Screenshots for (SM5) "SIGMA -The Blue Dasher-"

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#15]
![screen1](https://user-images.githubusercontent.com/63615036/173206646-9be3c34a-dfd0-4baf-a975-95c382e40faf.png)
![screen2](https://user-images.githubusercontent.com/63615036/173206647-8fb7cfc7-dd9a-4dcb-9423-6a9e94940ea0.png)
![screen3](https://user-images.githubusercontent.com/63615036/173206648-3e46c919-2ebe-4399-aab4-58b76f14c085.png)
![screen4](https://user-images.githubusercontent.com/63615036/173206649-299272ee-f35c-4395-ad6c-cc1e6172140e.png)

**Comment by JoseVarelaP** [comment]
Added! Thanks for the screenshots!
https://josevarela.xyz/SMArchive/Themes/ThemePreview.html?Category=StepMania%205&ID=SIGMA
