### ISSUE TITLE
Screenshots for (SM5) "XV"

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#16]
![screen1](https://user-images.githubusercontent.com/63615036/173425867-b54d152d-f541-4163-83ce-8d5867f78b39.png)
![screen2](https://user-images.githubusercontent.com/63615036/173425878-e641a06c-50c5-476b-b16a-14e0432561b5.png)
![screen3](https://user-images.githubusercontent.com/63615036/173425886-34999c25-87d2-4a11-b8cf-6901929ad8ba.png)
![screen4](https://user-images.githubusercontent.com/63615036/173425890-43965f8b-5431-47be-bfb3-7edfd8ce63e2.png)
![screen5](https://user-images.githubusercontent.com/63615036/173425892-d2317308-5cbe-42bb-a967-d8aa3714e9a7.png)
![screen6](https://user-images.githubusercontent.com/63615036/173425893-8bad3c50-ab80-4342-9c8f-2d8723acc640.png)

**Comment by JoseVarelaP** [comment]
Added the screenshots.
https://josevarela.xyz/SMArchive/Themes/ThemePreview.html?Category=StepMania%205&ID=XV
