### ISSUE TITLE
Screenshots for (SM5) "Cyberia Style 7 -metal system-"

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#19]
![screen1](https://user-images.githubusercontent.com/63615036/184248792-9589729e-dfb1-44d1-b0a6-761fdfc4a7f8.png)
![screen2](https://user-images.githubusercontent.com/63615036/184248795-a64613bd-1b97-4f68-af96-2563e141ab04.png)
![screen3](https://user-images.githubusercontent.com/63615036/184248800-79285663-6c9d-4747-a21f-0c8c536f4304.png)
![screen4](https://user-images.githubusercontent.com/63615036/184248804-657e50f2-d436-4432-bcbe-5518b47f7126.png)
![screen5](https://user-images.githubusercontent.com/63615036/184248808-7023fc48-883b-4b95-86b6-40897e305ebb.png)

**Comment by JoseVarelaP** [comment]
Added the images.
