### ISSUE TITLE
Screenshots for (SM5) "TK Mix"

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#22]
![screen1](https://user-images.githubusercontent.com/63615036/184660084-b01ca98f-0f58-48ce-98d7-f97a325c3b9e.png)
![screen2](https://user-images.githubusercontent.com/63615036/184660092-0ab4f686-dcee-4ba8-867e-5651906846d0.png)
![screen3](https://user-images.githubusercontent.com/63615036/184660101-346cb0de-8278-4198-aae3-62ec8d1a6379.png)
![screen4](https://user-images.githubusercontent.com/63615036/184660103-bc068033-1ed4-4032-8998-a8c46056117f.png)
![screen5](https://user-images.githubusercontent.com/63615036/184660110-8f633711-b769-40d7-aaf8-e89f3b3939c8.png)

**Comment by JoseVarelaP** [comment]
Added.
https://josevarela.xyz/SMArchive/Themes/ThemePreview.html?Category=StepMania%205&ID=TKMix
