### ISSUE TITLE
Screenshots for (Project OutFox) "In The Groove - GrooveNights"

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#23]
![screen1](https://user-images.githubusercontent.com/63615036/185761582-28b2032b-0927-4514-8ef1-933153e22d0b.png)
![screen2](https://user-images.githubusercontent.com/63615036/185761585-d09c5a4b-7ee6-4cfe-bc82-695b6482be27.png)
![screen3](https://user-images.githubusercontent.com/63615036/185761589-9b09bccc-d81b-4b05-ada3-95a61bbf6f88.png)
![screen4](https://user-images.githubusercontent.com/63615036/185761593-f7acb3e3-c65b-4646-ac98-645d56f8b1d3.png)
![screen5](https://user-images.githubusercontent.com/63615036/185761597-f05173c7-18f7-4c27-8bde-60370f9b0b56.png)

**Comment by JoseVarelaP** [comment]
Added the screenshots.
https://josevarela.xyz/SMArchive/Themes/ThemePreview.html?Category=OutFox&ID=GN
