### ISSUE TITLE
Screenshots for (Project OutFox) "superuser" (1.5.0)

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#25]
![2022-11-28_174449](https://user-images.githubusercontent.com/63615036/204335726-c042ed1e-0adf-4b29-a0bb-2d06299a8430.png)
![2022-11-28_174625](https://user-images.githubusercontent.com/63615036/204335712-43f086ec-db7f-431e-a9ec-5ceb056642d6.png)
![2022-11-28_174808](https://user-images.githubusercontent.com/63615036/204335721-fed5eb4f-a2a9-4026-b0af-dbfae23fed58.png)
![2022-11-28_175001](https://user-images.githubusercontent.com/63615036/204335724-c8cae643-e3e4-40fe-836f-3c952817a8cf.png)

**Comment by JoseVarelaP** [comment]
Added the screenshots.
https://josevarela.xyz/SMArchive/Themes/ThemePreview.html?Category=OutFox&ID=Superuser
