### ISSUE TITLE
Screenshots for (Project OutFox) "EKS-D ParaMania" (Alpha 3.5)

### ISSUE THREAD

**Issue by JustMoneko** [JoseVarelaP/StepMania-Archive#26]
![2022-12-14_105710](https://user-images.githubusercontent.com/63615036/207570535-b0a38fbf-562c-43ba-bdc0-67b183ca8bb7.png)
![2022-12-14_110043](https://user-images.githubusercontent.com/63615036/207570540-6cd94705-ce25-4444-a774-d6958c7944c2.png)
![2022-12-14_110221](https://user-images.githubusercontent.com/63615036/207570543-0779eaad-4dfd-4b7c-9a94-604066f2bc6e.png)
![2022-12-14_110537](https://user-images.githubusercontent.com/63615036/207570547-c8061168-c935-4911-a28d-4be189ed70f0.png)

**Comment by JoseVarelaP** [comment]
Added the screenshots.
https://josevarela.xyz/SMArchive/Themes/ThemePreview.html?Category=OutFox&ID=EKS-D
