### ISSUE TITLE
Screenshots for DDR-A3 (Curilang Edit) [StepMania 5 theme]

### ISSUE THREAD

**Issue by MattMayuga** [JoseVarelaP/StepMania-Archive#29]
これらのスクリーンショットはアーカイブ用にアップロードされた。
These were uploaded for the archive.

![CurilangA3-1](https://github.com/JoseVarelaP/StepMania-Archive/assets/26103475/f8c33fd8-486a-4ea6-a93b-db79375af075)
![CurilangA3-2](https://github.com/JoseVarelaP/StepMania-Archive/assets/26103475/83355533-c784-487e-91c7-3c0034f5e09b)
![CurilangA3-3](https://github.com/JoseVarelaP/StepMania-Archive/assets/26103475/9b9c7a5d-0254-4d20-bc3f-dda55cbcc8b1)
![CurilangA3-4](https://github.com/JoseVarelaP/StepMania-Archive/assets/26103475/228ae004-a969-40ec-abf6-a640c39e9c86)
![CurilangA3-5](https://github.com/JoseVarelaP/StepMania-Archive/assets/26103475/02bf9606-7969-4d13-8c29-46b5096403ad)
![CurilangA3-6](https://github.com/JoseVarelaP/StepMania-Archive/assets/26103475/cdb29b8d-7ae7-4892-9723-5e3a7a3c9869)

**Comment by JoseVarelaP** [comment]
Added the screenshots.
https://josevarela.net/SMArchive/Themes/ThemePreview.php?Category=StepMania%205&ID=DDRA3Curilang
