### ISSUE TITLE
Screenshots for CyberiaStyle 6 -consciousness to cyber 

### ISSUE THREAD

**Issue by Hahahaha1Ha** [JoseVarelaP/StepMania-Archive#30]
![screen00005 (1)](https://github.com/JoseVarelaP/StepMania-Archive/assets/107333584/ae3beaea-fca3-401e-adf4-7dc0a64fb607)

![screen00005 (2)](https://github.com/JoseVarelaP/StepMania-Archive/assets/107333584/29dd4ce2-98da-42c4-9156-010cdfecddab)
![screen00005 (3)](https://github.com/JoseVarelaP/StepMania-Archive/assets/107333584/c4b0edd2-cc3c-4767-9442-cf84b698de9d)

![screen00005 (4)](https://github.com/JoseVarelaP/StepMania-Archive/assets/107333584/370f9221-8aa7-4e5c-8072-b47953b256e5)

![screen00005 (5)](https://github.com/JoseVarelaP/StepMania-Archive/assets/107333584/a3845687-ba74-4113-83dc-eda5f81d7d00)

**Comment by JoseVarelaP** [comment]
Added the screenshots.
https://josevarela.net/SMArchive/Themes/ThemePreview.php?Category=SM3.9&ID=CS6
