### ISSUE TITLE
Screenshots for "N.PREX3 NeoStyle" theme (StepMania 3.9)

### ISSUE THREAD

**Issue by ThePlay0987654** [JoseVarelaP/StepMania-Archive#34]
![Clipboarder 2024 04 20-005](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/b37f20e3-2179-4a4e-9f0b-b52a841ac392)
![Clipboarder 2024 04 20-004](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/ae10b6e7-a57a-4f75-8bb4-d8d3e1c5d854)
![Clipboarder 2024 04 20-003](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/f81e9f10-3334-4686-950a-e0ce137e9b5a)
![Clipboarder 2024 04 20-002](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/4e294f37-3653-40a1-b8c5-249dd15bff8a)
![Clipboarder 2024 04 20](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/9301a553-07d8-4854-9966-ab9dc164fd30)

**Comment by JoseVarelaP** [comment]
Added to the archive.
https://josevarlea.net/SMArchive/Themes/ThemePreview.php?Category=SM3.9&ID=NPREX3
