### ISSUE TITLE
Screenshots for "Cityscape" theme (StepMania 3.9)

### ISSUE THREAD

**Issue by ThePlay0987654** [JoseVarelaP/StepMania-Archive#35]
![Clipboarder 2024 04 20-011](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/3057ba06-6fcb-414a-85aa-d1ca9df5d427)
![Clipboarder 2024 04 20-010](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/647fadc5-e37d-44b5-9d66-a2dffa287f2e)
![Clipboarder 2024 04 20-009](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/8d4f1687-ae15-4ede-931d-28ed3fed1f3e)
![Clipboarder 2024 04 20-008](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/90acf554-9c0c-4e9f-8c10-796d0ce0956c)
![Clipboarder 2024 04 20-007](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/3c9bf0d4-fc94-43b5-acb0-f1e5568ca0c6)
![Clipboarder 2024 04 20-006](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/ae8ecfce-fa5e-401c-84ad-a1882315fc9b)

**Comment by JoseVarelaP** [comment]
Added to the archive.
https://josevarlea.net/SMArchive/Themes/ThemePreview.php?Category=SM3.9&ID=CitySc
