### ISSUE TITLE
Sceenshots for "ForeverBlue2" theme (StepMania 3.9)

### ISSUE THREAD

**Issue by ThePlay0987654** [JoseVarelaP/StepMania-Archive#36]
![Clipboarder 2024 04 20-013](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/fdb6bf39-4291-4121-b555-b0ceabaa1db9)
![Clipboarder 2024 04 20-014](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/1c56eff4-2b81-40d2-8fef-30d05a5a1ad3)
![Clipboarder 2024 04 20-015](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/fe89eaf7-5c6e-4a88-9f60-3cb83b9a9c38)
![Clipboarder 2024 04 20-016](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/3a93b8fa-33df-4710-9749-98cc8524eda9)
![Clipboarder 2024 04 20-017](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/6591e983-0f21-4a91-80cc-e59f37c410b6)
![Clipboarder 2024 04 20-018](https://github.com/JoseVarelaP/StepMania-Archive/assets/167587104/a2a6cafe-f2bd-4d76-9393-ec8055957f42)

**Comment by JoseVarelaP** [comment]
Added to the archive.
https://josevarela.net/SMArchive/Themes/ThemePreview.php?Category=SM3.9&ID=FB2
