### ISSUE TITLE
Noteskin missed in CyberiaStyle series

### ISSUE THREAD

**Issue by X7sd** [JoseVarelaP/StepMania-Archive#9]
CyberiaStyle themes should have two sets of Noteskin with it in every version since CyberiaStyle 4. But they are not included in your archive. Could you please add them to your archive? Thank you.
The missed Noteskins are named as "**cyb**" and "**cyb-note**". Noteskins are in the folder "Noteskins", but not "Themes" folder.

**Comment by JoseVarelaP** [comment]
Oh right, that's a good point. They were given to me as just the theme files, however I have the zips with the entire smzip's on them, so i'll get those up.
